# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07f13d931ccdea75ec86a34e4ac1bf335edc5b9e62a382151e6d42068d629d51cd435a6d3643c43f7c6b54863eb6bdab2316ec78172c4ce08728baf5b572f518

test:
  secret_key_base: 7df2c7a2dfca7879c6d03642b846d890019e495c9bafb112b068c2fe92d5c12be974f6143d5aff370f1da4d76e4b6e1b761be013afe9088e4d9bec8ae63b84b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
